baseURL = "/"
languageCode = "en-us"
title = "Cheatsheet Maker"
copyright = ""
disqusShortname = ""
enableEmoji = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "emacs"
ignoreFiles = ["\\.scss$"]
